const PDFDocument = require('pdfkit');

/**
 * Generate a result PDF and pipe it to the response stream.
 * @param {Object} res - Express response
 * @param {Object} attempt - Attempt document (populated)
 * @param {Object} user - User document
 */
const generateResultPDF = (res, attempt, user) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=result-${attempt._id}.pdf`);
    doc.pipe(res);

    // ── Header ─────────────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill('#1e40af');
    doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text('SmartMCQ Pro', 50, 20);
    doc.fontSize(12).font('Helvetica').text('Exam Result Report', 50, 50);
    doc.fillColor('#000000').moveDown(3);

    // ── Candidate Info ─────────────────────────────────────────────────────────
    doc.fontSize(14).font('Helvetica-Bold').text('Candidate Information', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text(`Name: ${user.name}`);
    doc.text(`Email: ${user.email}`);
    doc.text(`Date: ${new Date(attempt.createdAt).toLocaleDateString('en-IN', { dateStyle: 'long' })}`);
    doc.text(`Mode: ${attempt.mode.charAt(0).toUpperCase() + attempt.mode.slice(1)}`);
    doc.moveDown(1);

    // ── Score Summary ──────────────────────────────────────────────────────────
    doc.fontSize(14).font('Helvetica-Bold').text('Performance Summary', { underline: true });
    doc.moveDown(0.5);

    const summaryData = [
        ['Score', `${attempt.score} / ${attempt.maxScore}`],
        ['Accuracy', `${attempt.accuracy.toFixed(1)}%`],
        ['Total Questions', attempt.totalQuestions],
        ['Correct', attempt.correctCount],
        ['Wrong', attempt.wrongCount],
        ['Skipped', attempt.skippedCount],
        ['Time Taken', `${Math.floor(attempt.timeTaken / 60)}m ${attempt.timeTaken % 60}s`],
    ];

    summaryData.forEach(([label, value]) => {
        doc.fontSize(11).font('Helvetica-Bold').text(`${label}: `, { continued: true });
        doc.font('Helvetica').text(String(value));
    });

    if (attempt.weakSubjects && attempt.weakSubjects.length > 0) {
        doc.moveDown(0.5);
        doc.fontSize(11).font('Helvetica-Bold').text('Weak Subjects: ', { continued: true });
        doc.font('Helvetica').text(attempt.weakSubjects.join(', '));
    }

    doc.moveDown(1);

    // ── Question Review ────────────────────────────────────────────────────────
    if (attempt.answers && attempt.answers.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Question Review', { underline: true });
        doc.moveDown(0.5);

        attempt.answers.forEach((ans, i) => {
            const q = ans.questionId || {};
            const questionText = q.question || ans.questionText || `Question ${i + 1}`;
            
            const status = ans.isCorrect ? '✓ Correct' : ans.selectedOption ? '✗ Wrong' : '— Skipped';
            const color = ans.isCorrect ? '#16a34a' : ans.selectedOption ? '#dc2626' : '#6b7280';

            // Auto page break
            if (doc.y > doc.page.height - 150) doc.addPage();

            doc.fontSize(10).font('Helvetica-Bold').fillColor('#000000');
            doc.text(`Q${i + 1}. ${questionText}`, { width: 500 });

            const ansText = ans.selectedText ? `${ans.selectedOption || 'None'} (${ans.selectedText})` : (ans.selectedOption || 'None');
            const corText = ans.correctText ? `${ans.correctOption} (${ans.correctText})` : ans.correctOption;

            doc.fontSize(9).font('Helvetica').fillColor(color);
            doc.text(`${status}   |   Your Answer: ${ansText}`, { continued: true });
            doc.fillColor('#000000').text(`   |   Correct: ${corText}`);
            doc.moveDown(0.5);
        });
    }

    // ── Footer ─────────────────────────────────────────────────────────────────
    doc.moveDown(2);
    doc.fontSize(9).fillColor('#6b7280').text('Generated by SmartMCQ Pro — smartmcqpro.com', { align: 'center' });

    doc.end();
};

module.exports = { generateResultPDF };
